### ISSUE TITLE
question after reading code

### ISSUE THREAD

**Issue by shian** [uwiger/gproc#112]
After reading the code, I found this line https://github.com/uwiger/gproc/blob/master/src/gproc_pool.erl#L384

What is different between `(N rem Sz-1) + 1 ` and `N rem Sz` ?
Is this some kind of performance tips ?

**Comment by uwiger** [comment]
No, just stupid.

But if you can suggest a clever justification for it, I'll buy you a beer. ;-)

**Comment by shian** [comment]
Thanks for clarify
