### ISSUE TITLE
Use a explicit pid() instead of the implicit self() to subscribe

### ISSUE THREAD

**Issue by posilva** [uwiger/gproc#117]
Hi,

I would like to know if it's possible to register a explicit pid() instead of the implicit self() pid? (I would do the PR :) )

My use case is: 
- I would like to make a supervisor that registers all the childs to an event.

Thank you

**Comment by uwiger** [comment]
I believe this is what you're looking for:
https://github.com/uwiger/gproc/blob/master/doc/gproc.md#reg_other-2

**Comment by posilva** [comment]
That's it. Thank you!
