### ISSUE TITLE
gproc dist and rebar3?

### ISSUE THREAD

**Issue by drozzy** [uwiger/gproc#119]
How can I enable gproc_dist in rebar3 shell?

I've tried:
```
    GPROC_DIST=true ./rebar3 shell --sname foo
```

and still get the error if I try to register globally:
```
** exception error: local_only
     in function  gproc:reg/1
        called as gproc:reg({p,g,{asdf,asdf}})

```

**Comment by uwiger** [comment]
Could you checkout PR #120 ?

It automatically starts the gproc app too.

**Comment by drozzy** [comment]
Hm.. just tried but it seems like the same error. The issue is that it starts in "local_only" mode by default. How can I switch it to global?

P.S.: Any reason for not starting it in global by default?

**Comment by drozzy** [comment]
My rebar3 dep:

```
  {gproc, {git, "https://github.com/uwiger/gproc.git", 
            {ref, "4dd2718099f26607ccbaf138ed1f8f6e77290f3c"} 
          }
```

My shell:
```
$ GPROC_DIST=true ./rebar3 shell
1> gproc:reg({p, g, {hey, man}}).
** exception error: local_only
     in function  gproc:reg/1
        called as gproc:reg({p,g,{hey,man}})

```

**Comment by uwiger** [comment]
Ok, my patch enabled starting gproc in global mode, with gproc as the top app.

```shell
$ GPROC_DIST=true rebar3 shell
===> Verifying dependencies...
===> Compiling gproc
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V7.3.1  (abort with ^G)
1> ===> The rebar3 shell is a development tool; to deploy applications in production, consider using releases (http://www.rebar3.org/v3.0/docs/releases)
===> Booted gproc

1> gproc:reg({n,g,k1}).
true
2> 
```

If you have your own application, with gproc as a dependency, you can enable global mode by setting the gproc environment variable `{gproc_dist, all}`. If you don't have any other environment variables to set, you can reuse the technique in gproc's `rebar.config.script`:

```erlang
{shell, [{config, "dist_shell.config"}]}
```

**Comment by drozzy** [comment]
Thanks.
