### ISSUE TITLE
write_concurrency on oredered_set has no effect?

### ISSUE THREAD

**Issue by benbro** [uwiger/gproc#131]
The [ets doc](http://erlang.org/doc/man/ets.html) says about {write_concurrency,boolean()}:
```Table type ordered_set is not affected by this option```

https://github.com/uwiger/gproc/blob/master/src/gproc.erl#L2748

**Comment by uwiger** [comment]
This is true. It never did have any effect. The docs should say that. :)

Hopefully, OTP will eventually introduce an ordered_set type that actually scales with multiple cores. There are prototypes, but nothing in the pipeline, as far as I know.

**Comment by benbro** [comment]
Thanks
