### ISSUE TITLE
Use a stable app version number

### ISSUE THREAD

**Issue by leoliu** [uwiger/gproc#184]
I want to use gproc git master however unlike other projects it has a volatile version number. For example the gproc app directory in my release is `gproc-0.8.0+build.360.ref378bd274`. This seems to have little use and always gets in the way because it changes constantly. For locking versions `rebar.lock` already does and for the whole project. Thanks for consideration.

**Comment by tsloughter** [comment]
It changes if the latest commit to master changes. It is useful information that tells you this isn't version `0.8.0` but is a version after it at commit ref `378bd274`.

**Comment by leoliu** [comment]
For me It proves cumbersome having the version number changed on every commit. So soon after reporting this bug I have reverted to gproc from hex to have peace of mind :)
