### ISSUE TITLE
Relase for OTP 24

### ISSUE THREAD

**Issue by benbro** [uwiger/gproc#186]
Is it possible to make a new release?
Master seams to be compatible with OTP 24 but the last 0.8.0 release isn't.
https://github.com/uwiger/gproc/issues/164
https://github.com/uwiger/gproc/pull/182

**Comment by uwiger** [comment]
Current master tagged as `0.9.0` and published to [hex.pm](https://hex.pm/packages/gproc)

**Comment by benbro** [comment]
Thanks!
