### ISSUE TITLE
gproc_dist_tests: dist_test_...*timed out*

### ISSUE THREAD

**Issue by matwey** [uwiger/gproc#51]
Hi, I am suffering an issue similar to #44 on the latest master. 
See the eunit log: http://susepaste.org/27740609

The difference is that failure is reproduced only approx 3 times per 50 runs (on my PC). I've just been running rebar eunit in a loop. Increasing timeout up to 240 seems to make failure probability as low as no failures per 50 runs.

Not sure if that test is deterministic...

**Comment by uwiger** [comment]
I've just merged some changes that should at least take care of the timeout in `t_follow_monitor/1`.

**Comment by manuel-rubio** [comment]
if @matwey isn't complaining it's meaning it's fixed. @uwiger I think you can close the ticket.

**Comment by matwey** [comment]
Lets close this. I'll reopen if required
