### ISSUE TITLE
gproc_dist:unreg({p, g, _}) fails to delete an entry in slave nodes 

### ISSUE THREAD

**Issue by massn** [uwiger/gproc#87]
Hi,

I noticed `gproc_dist:unreg/1` does not work well with a property in the global scope. It seems to me that the leader (master) deletes an entry from its ets, but the slaves do not correctly. They receive `remove_globals` message, but do not delete their entries fully.

In `gproc_dist.erl`, 

```erlang
delete_globals(Globals) ->
    lists:foreach(
      fun({{_,g,_},T} = K) when is_atom(T) ->
              ets:delete(?TAB, K);
         ({Key, Pid}) when is_pid(Pid); Pid==shared ->
              ets:delete(?TAB, {Pid, Key});  %% here!
         ({Pid, Key}) when is_pid(Pid); Pid==shared ->
	      ets:delete(?TAB, {Pid, Key})
      end, Globals).
```
I think the marked line (https://github.com/uwiger/gproc/blob/master/src/gproc_dist.erl#L800) should be

```erlang
ets:delete(?TAB, {Key, Pid});
```
or `{Key, Pid}` is inverted now.

I modified it and got an expected result in my brunch.

Thank you in advance.

**Comment by panii** [comment]
I found this problem too. I spend hours to find where goes wrong last night. Finally I located the code where massn mentioned. I think massn is correct.

**Comment by massn** [comment]
@panii 
@uwiger 
Thank you very much for your responses and code fix !!

**Comment by uwiger** [comment]
If you're satisfied with the solution, I'll go ahead and merge it into master.

**Comment by massn** [comment]
I have checked out your code fix and got expected results. I am satisfied with your solution.
Please merge it into master.
If you don't mind, could you tag the new master branch?

**Comment by uwiger** [comment]
Merged and tagged as 0.4 (perhaps it's time for a 1.0 soon ...)

**Comment by massn** [comment]
Thank you very much.
I am looking forward to 1.0 !!!

**Comment by panii** [comment]
Thank you very much indeed!
